workflows:
  android-workflow:
    name: Android Release
    max_build_duration: 60
    environment:
      flutter: stable
      groups:
        - Thailingo
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Set up keystore
        script: |
          echo $KEYSTORE_FILE | base64 --decode > thailingo-release.jks
          cat >> android/key.properties <<EOF
          storePassword=$KEYSTORE_PASSWORD
          keyPassword=$KEY_PASSWORD
          keyAlias=$KEY_ALIAS
          storeFile=../../thailingo-release.jks
          EOF
      - name: Build Android APK
        script: |
          flutter build apk --release
      - name: Publish to Firebase App Distribution
        script: |
          echo $FIREBASE_SERVICE_ACCOUNT | base64 --decode > firebase-service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/firebase-service-account.json
          firebase appdistribution:distribute \
            build/app/outputs/flutter-apk/app-release.apk \
            --app $FIREBASE_APP_ID \
            --groups Testers \
            --release-notes "New build"
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk